const $=id=>document.getElementById(id);
const UPT_BLOCK=15, UPT_RATE=5, SOS_GRACE=5, EOS_GRACE=5, LUNCH_GRACE=3, LUNCH_MIN=30;
const STORAGE_KEY="time-calculator-state-v5", SAVE_FLAG="time-calculator-save-v5", THEME_KEY="time-calculator-theme-v1";
let mode="earliest";
const stateIds=["enableUpt","enableFlex","enableStandard","uptHours","uptMinutes","flexHours","flexMinutes","standardHours","standardMinutes","shiftStart","shiftEnd","lunchStart","graceEnabled","metEnabled","desiredLeave","protectBalance","ptoOrder","predictStart","predictEnd","predictLunchEnabled","predictLunchOut","predictLunchIn","actualClockIn","actualClockOut","attendanceLunchEnabled","actualLunchOut","actualLunchIn"];

function num(id){const v=Number($(id).value);return Number.isFinite(v)?Math.max(0,v):0}
function parseTime(v){if(!v||!v.includes(":"))return null;const[h,m]=v.split(":").map(Number);return h*60+m}
function normalizeEnd(start,end){return end<=start?end+1440:end}
function normalizeAfter(value,anchor){let t=value;while(t<anchor)t+=1440;return t}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function displayClock(x){if(x==null)return"—";const m=((Math.round(x)%1440)+1440)%1440,h24=Math.floor(m/60),mm=m%60,h=h24%12||12;return`${h}:${String(mm).padStart(2,"0")} ${h24>=12?"PM":"AM"}`}
function displayDuration(x){x=Math.max(0,Math.round(x));const h=Math.floor(x/60),m=x%60;if(h&&m)return`${h} hr ${m} min`;if(h)return`${h} hr${h===1?"":"s"}`;return`${m} min`}
function roundUpt(x){return x>0?Math.ceil(x/UPT_BLOCK)*UPT_BLOCK:0}

function getSchedule(){const start=parseTime($("shiftStart").value),rawEnd=parseTime($("shiftEnd").value),rawLunch=parseTime($("lunchStart").value);if(start==null||rawEnd==null||rawLunch==null)return null;let end=normalizeEnd(start,rawEnd);if($("metEnabled").checked)end+=60;const lunchStart=normalizeAfter(rawLunch,start),lunchEnd=lunchStart+LUNCH_MIN;return{start,end,lunchStart,lunchEnd,grace:$("graceEnabled").checked,met:$("metEnabled").checked}}
function enabledBalance(kind){const enabled=$(kind==="upt"?"enableUpt":kind==="flex"?"enableFlex":"enableStandard").checked;if(!enabled)return 0;const p=kind==="standard"?"standard":kind;return Math.round(num(p+"Hours")*60+num(p+"Minutes"))}
function usableUpt(){return Math.floor(enabledBalance("upt")/15)*15}
function balances(){return{upt:usableUpt(),rawUpt:enabledBalance("upt"),flex:enabledBalance("flex"),standard:enabledBalance("standard")}}
function totalCapacity(){const b=balances();return b.upt+b.flex+b.standard}

function splitPaid(p,b,protect){let flex=0,standard=0;if(protect==="flex"){standard=Math.min(b.standard,p);flex=p-standard}else if(protect==="standard"){flex=Math.min(b.flex,p);standard=p-flex}else if($("ptoOrder").value==="standard_first"){standard=Math.min(b.standard,p);flex=p-standard}else{flex=Math.min(b.flex,p);standard=p-flex}if(flex>b.flex||standard>b.standard||flex<0||standard<0)return null;return{flex,standard}}
function planFor(required){required=Math.max(0,Math.round(required));const b=balances(),protect=$("protectBalance").value,c=[];for(let paid=0;paid<=Math.min(required,b.flex+b.standard);paid++){const rem=required-paid,upt=roundUpt(rem);if(upt>b.upt)continue;const split=splitPaid(paid,b,protect);if(!split)continue;const total=paid+upt,over=Math.max(0,total-required);let score;if(protect==="upt")score=[upt,over,paid];else if(protect==="flex")score=[split.flex,upt,over,split.standard];else score=[split.standard,upt,over,split.flex];c.push({required,upt,flex:split.flex,standard:split.standard,total,over,rawUpt:b.rawUpt,score})}c.sort((a,b)=>{for(let i=0;i<Math.max(a.score.length,b.score.length);i++){const d=(a.score[i]||0)-(b.score[i]||0);if(d)return d}return 0});return c[0]||null}

function normalizeTarget(raw,s){return normalizeAfter(raw,s.start)}
function coverageRequiredForFinalLeave(target,s){if(target>=s.end)return 0;if(s.grace&&target>=s.end-EOS_GRACE)return 0;return Math.max(0,s.end-target)}
function updateVisibility(){$("uptInputs").classList.toggle("hidden",!$("enableUpt").checked);$("flexInputs").classList.toggle("hidden",!$("enableFlex").checked);$("standardInputs").classList.toggle("hidden",!$("enableStandard").checked);$("resultCard").classList.add("hidden");maybeSave()}
function setMode(m){mode=m;$("modeEarliest").classList.toggle("active",m==="earliest");$("modeDesired").classList.toggle("active",m==="desired");$("desiredWrap").classList.toggle("hidden",m!=="desired");$("resultCard").classList.add("hidden");maybeSave()}
function updateScheduleUI(){const s=getSchedule();if(!s)return;$("shiftSummary").textContent=`${displayClock(s.start)} → ${displayClock(s.end)}${s.met?" · MET +1 hr":""} · Lunch ${displayClock(s.lunchStart)}–${displayClock(s.lunchEnd)}`;$("lunchDisplay").textContent=`${displayClock(s.lunchStart)}–${displayClock(s.lunchEnd)}`;$("graceSummary").classList.toggle("hidden",!s.grace);if(s.grace)$("graceSummary").textContent=`SOS ${displayClock(s.start-SOS_GRACE)}–${displayClock(s.start+SOS_GRACE)} · Lunch ${displayClock(s.lunchStart-LUNCH_GRACE)}–${displayClock(s.lunchStart+LUNCH_GRACE)} / ${displayClock(s.lunchEnd-LUNCH_GRACE)}–${displayClock(s.lunchEnd+LUNCH_GRACE)} · EOS ${displayClock(s.end-EOS_GRACE)}–${displayClock(s.end+EOS_GRACE)}`;maybeSave()}
function renderResult(o){const c=$("resultCard");c.classList.toggle("error",!!o.error);$("resultKicker").textContent=o.kicker;$("resultTime").textContent=o.time;$("resultMessage").textContent=o.message;$("resultNeeded").textContent=o.needed;$("resultUsed").textContent=o.used;$("resultUpt").textContent=o.upt;$("resultFlex").textContent=o.flex;$("resultStandard").textContent=o.standard;$("resultGrace").textContent=o.grace;$("resultExtra").textContent=o.extra||"";c.classList.remove("hidden");setTimeout(()=>c.scrollIntoView({behavior:"smooth",block:"nearest"}),60)}

function calculateEarliest(s){const cap=totalCapacity(),graceOnly=s.grace?EOS_GRACE:0;let target=s.end-Math.max(cap,graceOnly);target=Math.max(s.start,target);const required=coverageRequiredForFinalLeave(target,s);if(required===0){renderResult({kicker:"Earliest you can leave",time:displayClock(target),message:s.grace?"This punch is covered by the actual EOS grace window. Your balances stay untouched.":"No time balance is needed.",needed:"0 min",used:"0 min",upt:"0 min",flex:"0 min",standard:"0 min",grace:s.grace?"EOS grace":"Off"});return}const plan=planFor(required);if(!plan){renderResult({error:true,kicker:"Unable to cover",time:displayClock(s.end),message:"The enabled balances cannot cover an earlier punch.",needed:displayDuration(required),used:"0 min",upt:"0 min",flex:"0 min",standard:"0 min",grace:"Not used"});return}const extras=[];if(plan.over)extras.push(`UPT rounding adds ${displayDuration(plan.over)} beyond the exact uncovered time.`);if(plan.upt&&plan.rawUpt-plan.upt>=0)extras.push(`UPT remaining after this plan: ${displayDuration(plan.rawUpt-plan.upt)}.`);renderResult({kicker:"Earliest you can leave",time:displayClock(target),message:"This time is outside EOS grace, so the full gap to the actual EOS must be covered.",needed:displayDuration(required),used:displayDuration(plan.total),upt:displayDuration(plan.upt),flex:displayDuration(plan.flex),standard:displayDuration(plan.standard),grace:"Not used",extra:extras.join(" ")})}
function calculateDesired(s){const raw=parseTime($("desiredLeave").value);if(raw==null)return;const target=normalizeTarget(raw,s);if(target<s.start||target>s.end){renderResult({error:true,kicker:"Outside actual shift",time:displayClock(target),message:`Choose a time between ${displayClock(s.start)} and ${displayClock(s.end)}.`,needed:"—",used:"—",upt:"—",flex:"—",standard:"—",grace:"—"});return}const required=coverageRequiredForFinalLeave(target,s);if(required===0){renderResult({kicker:"Yes — you can leave at",time:displayClock(target),message:s.grace&&target<s.end?"This punch is inside the actual EOS grace window. No PTO or UPT is needed.":"No time off is needed.",needed:"0 min",used:"0 min",upt:"0 min",flex:"0 min",standard:"0 min",grace:s.grace&&target<s.end?"EOS grace":"Not needed"});return}const plan=planFor(required);if(plan){const extras=[];if(plan.over)extras.push(`UPT rounding adds ${displayDuration(plan.over)}.`);if(plan.upt)extras.push(`UPT remaining: ${displayDuration(Math.max(0,plan.rawUpt-plan.upt))}.`);if(target<=s.lunchStart)extras.push("Because you leave before lunch, the lunch period is part of the absence and is not subtracted.");renderResult({kicker:"Yes — you can leave at",time:displayClock(target),message:`The exact gap from your punch to the actual EOS is ${displayDuration(required)}.`,needed:displayDuration(required),used:displayDuration(plan.total),upt:displayDuration(plan.upt),flex:displayDuration(plan.flex),standard:displayDuration(plan.standard),grace:"Not used",extra:extras.join(" ")});return}const cap=totalCapacity();let earliest;if(s.grace&&cap<EOS_GRACE)earliest=s.end-EOS_GRACE;else earliest=Math.max(s.start,s.end-cap);const short=Math.max(0,required-cap);renderResult({error:true,kicker:"Earliest available time",time:displayClock(earliest),message:`You cannot cover ${displayClock(target)}. You're short by ${displayDuration(short)}.`,needed:displayDuration(required),used:displayDuration(cap),upt:displayDuration(usableUpt()),flex:displayDuration(enabledBalance("flex")),standard:displayDuration(enabledBalance("standard")),grace:s.grace&&cap<EOS_GRACE?"EOS grace":"Not used",extra:"Grace does not stack with PTO/UPT. If the punch is outside the actual EOS grace window, the full gap to EOS must be covered."})}
function calculate(){const s=getSchedule();if(!s)return;updateScheduleUI();mode==="desired"?calculateDesired(s):calculateEarliest(s);const b=$("calculateBtn"),old=b.textContent;b.textContent="Done ✓";setTimeout(()=>b.textContent=old,850);maybeSave()}

function earnedUpt(work){return Math.floor((Math.max(0,work)*UPT_RATE)/60+1e-9)}
function overlap(a1,a2,b1,b2){return Math.max(0,Math.min(a2,b2)-Math.max(a1,b1))}
function predictUpt(){const start=parseTime($("predictStart").value),rawEnd=parseTime($("predictEnd").value);if(start==null||rawEnd==null)return;const end=normalizeEnd(start,rawEnd);let lunch=0,note="";if($("predictLunchEnabled").checked){const loRaw=parseTime($("predictLunchOut").value),liRaw=parseTime($("predictLunchIn").value);if(loRaw!=null&&liRaw!=null){const lo=normalizeAfter(loRaw,start),li=normalizeAfter(liRaw,lo);lunch=overlap(start,end,lo,li)}}const worked=Math.max(0,end-start-lunch),earned=earnedUpt(worked);$("predictWorked").textContent=displayDuration(worked);$("predictEarned").textContent=displayDuration(earned);$("predictionResult").classList.remove("hidden");note=`${displayDuration(end-start)} elapsed${lunch?` − ${displayDuration(lunch)} actual lunch/off-clock time`:""} = ${displayDuration(worked)} actually worked. UPT earned = ${displayDuration(earned)} after rounding down to a whole minute.`;$("predictionNote").textContent=note;maybeSave()}

function attendanceGap(actualIn,actualOut,lunchOut,lunchIn,s,tookLunch){const grace=s.grace;let sos=0,lunch=0,eos=0;if(actualIn>s.start){if(!(grace&&actualIn<=s.start+SOS_GRACE))sos=actualIn-s.start}if(tookLunch&&lunchOut!=null&&lunchIn!=null){if(lunchOut<s.lunchStart&&!(grace&&lunchOut>=s.lunchStart-LUNCH_GRACE))lunch+=s.lunchStart-lunchOut;if(lunchIn>s.lunchEnd&&!(grace&&lunchIn<=s.lunchEnd+LUNCH_GRACE))lunch+=lunchIn-s.lunchEnd}if(actualOut<s.end){if(!(grace&&actualOut>=s.end-EOS_GRACE))eos=s.end-actualOut}return{sos,lunch,eos,total:sos+lunch+eos}}
function checkAttendance(){const s=getSchedule(),inRaw=parseTime($("actualClockIn").value),outRaw=parseTime($("actualClockOut").value);if(!s||inRaw==null||outRaw==null)return;let actualIn=normalizeAfter(inRaw,s.start-12*60),actualOut=normalizeAfter(outRaw,s.start);if(actualIn>s.start+720)actualIn-=1440;actualIn=Math.min(actualIn,s.end);actualOut=clamp(actualOut,s.start,s.end+240);let lo=null,li=null;const took=$("attendanceLunchEnabled").checked;if(took){const loRaw=parseTime($("actualLunchOut").value),liRaw=parseTime($("actualLunchIn").value);if(loRaw!=null&&liRaw!=null){lo=normalizeAfter(loRaw,s.start);li=normalizeAfter(liRaw,lo)}}const g=attendanceGap(actualIn,actualOut,lo,li,s,took),upt=roundUpt(g.total);$("startGap").textContent=displayDuration(g.sos);$("lunchGap").textContent=displayDuration(g.lunch);$("endGap").textContent=displayDuration(g.eos);$("totalGap").textContent=displayDuration(g.total);$("attendanceUpt").textContent=displayDuration(upt);$("attendanceResult").classList.remove("hidden");const notes=[];if(s.grace)notes.push(`Grace is checked independently: SOS ±5 min, lunch ±3 min, EOS ±5 min.`);else notes.push("Grace is turned off.");notes.push("Working early or late can increase UPT earned, but it never offsets a separate absence.");notes.push("The UPT amount shown rounds the total uncovered time up to the next 15-minute block.");$("attendanceNote").textContent=notes.join(" ");maybeSave()}

function toast(msg){const e=$("toast");e.textContent=msg;e.classList.add("show");clearTimeout(window.__tcToast);window.__tcToast=setTimeout(()=>e.classList.remove("show"),2200)}
async function shareSite(){try{if(navigator.share)await navigator.share({title:"Time Calculator",text:"UPT & PTO leave planner",url:location.href});else if(navigator.clipboard){await navigator.clipboard.writeText(location.href);toast("Link copied")}}catch(_){}}
function serialize(){const d={mode};stateIds.forEach(id=>{const e=$(id);d[id]=e.type==="checkbox"?e.checked:e.value});return d}
function maybeSave(){if(!$("saveEntries").checked)return;try{localStorage.setItem(SAVE_FLAG,"1");localStorage.setItem(STORAGE_KEY,JSON.stringify(serialize()))}catch(_){}}
function setSave(enabled){try{if(enabled){localStorage.setItem(SAVE_FLAG,"1");localStorage.setItem(STORAGE_KEY,JSON.stringify(serialize()));toast("Times & balances will be saved") }else{localStorage.removeItem(SAVE_FLAG);localStorage.removeItem(STORAGE_KEY);toast("Saved times & balances cleared")}}catch(_){}}
function loadSaved(){try{const on=localStorage.getItem(SAVE_FLAG)==="1";$("saveEntries").checked=on;if(!on)return;const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");if(d.mode==="desired"||d.mode==="earliest")mode=d.mode;stateIds.forEach(id=>{if(!(id in d))return;const e=$(id);e.type==="checkbox"?e.checked=!!d[id]:e.value=d[id]})}catch(_){}}
function applyTheme(t){const dark=t==="dark";document.body.dataset.theme=dark?"dark":"light";$("themeToggle").checked=dark;try{localStorage.setItem(THEME_KEY,dark?"dark":"light")}catch(_){}}
function loadTheme(){try{applyTheme(localStorage.getItem(THEME_KEY)==="dark"?"dark":"light")}catch(_){applyTheme("light")}}

$("modeEarliest").addEventListener("click",()=>setMode("earliest"));$("modeDesired").addEventListener("click",()=>setMode("desired"));
["enableUpt","enableFlex","enableStandard"].forEach(id=>$(id).addEventListener("change",updateVisibility));
$("calculateBtn").addEventListener("click",calculate);$("predictBtn").addEventListener("click",predictUpt);$("attendanceBtn").addEventListener("click",checkAttendance);$("shareBtn").addEventListener("click",shareSite);$("themeToggle").addEventListener("change",e=>applyTheme(e.target.checked?"dark":"light"));
$("editShiftBtn").addEventListener("click",()=>{$("shiftEditor").classList.toggle("hidden");$("editShiftBtn").textContent=$("shiftEditor").classList.contains("hidden")?"Edit":"Close"});$("doneShiftBtn").addEventListener("click",()=>{updateScheduleUI();$("shiftEditor").classList.add("hidden");$("editShiftBtn").textContent="Edit";$("resultCard").classList.add("hidden")});
$("predictLunchEnabled").addEventListener("change",e=>{$("predictLunchFields").classList.toggle("hidden",!e.target.checked);maybeSave()});$("attendanceLunchEnabled").addEventListener("change",e=>{$("attendanceLunchFields").classList.toggle("hidden",!e.target.checked);maybeSave()});$("saveEntries").addEventListener("change",e=>setSave(e.target.checked));
stateIds.forEach(id=>{const e=$(id);e.addEventListener("change",()=>{if(["shiftStart","shiftEnd","lunchStart","graceEnabled","metEnabled"].includes(id))updateScheduleUI();$("resultCard").classList.add("hidden");maybeSave()})});
loadTheme();loadSaved();setMode(mode);updateVisibility();updateScheduleUI();$("predictLunchFields").classList.toggle("hidden",!$("predictLunchEnabled").checked);$("attendanceLunchFields").classList.toggle("hidden",!$("attendanceLunchEnabled").checked);
if("serviceWorker" in navigator&&location.protocol.startsWith("http"))window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));